name: tally_up
description: A digital ledger fintech app
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  mobile_scanner: ^3.5.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true